### ISSUE TITLE
fuwafuwa not found, qobuz-get compiled for windows 32bits please

### ISSUE THREAD

**Issue by fabriccioguzman** [whiteisthenewblack/qobuz-get#1]
https://git.fuwafuwa.moe/albino/qobuz-get/releases

**Comment by whiteisthenewblack** [comment]
Hi, git.fuwafuwa.moe is currently down. I'm talking to the host now and it should be available again in the near future, but I'll upload the Windows binary here in just a second, hopefully.

**Comment by whiteisthenewblack** [comment]
This should be it.

[qobuz-get-win32-1.3.zip](https://github.com/whiteisthenewblack/qobuz-get/files/1599102/qobuz-get-win32-1.3.zip)

**Comment by fabriccioguzman** [comment]
thanks:)
