### ISSUE TITLE
I'm very stupid, so i didn't understand the setup

### ISSUE THREAD

**Issue by Creeptonit** [whiteisthenewblack/qobuz-get#10]
I put app id, app secret and user token, and now i have no idea what to do.
If i open InitEnvironment, cmd opens and nothing happens.
Qobuz_Get closes in one second.
I have no idea what to do after putting everything in magic.json
pls help

**Comment by albino** [comment]
You need to call `qobuz-get` with the URL/id of the album you wish to download.

For example: `qobuz-get 763263`

Edit: to clarify, you run this command in the `cmd` window produced by `InitEnvironment.bat`

**Comment by Creeptonit** [comment]
In Init?

**Comment by albino** [comment]
What do you mean?

**Comment by Creeptonit** [comment]
In InitEnvironment or where?

**Comment by albino** [comment]
>Edit: to clarify, you run this command in the cmd window produced by InitEnvironment.bat

You should also know that the program may well not work in Windows at the moment. I don't have a machine to test it with.

**Comment by Creeptonit** [comment]
Oh, thanks

**Comment by albino** [comment]
Let me know whether it works for you :-)

**Comment by Creeptonit** [comment]
Do you plan 24 bit downloading? Or i can?

**Comment by albino** [comment]
I don't have a good enough Qobuz subscription to download 24 bit, so I'm unable to implement that, sorry.
