### ISSUE TITLE
hi have error 0x80004005 trying open qobuz get 

### ISSUE THREAD

**Issue by ali2134** [whiteisthenewblack/qobuz-get#6]
this happening me in win10, any fix?

**Comment by FatKiwi** [comment]
You have corrupted system.

Try `sfc /scannow`

**Comment by ali2134** [comment]
are you telling me it's working on win10? which version?

**Comment by ali2134** [comment]
solved but i still don't know how works the app, may i request gui app?

**Comment by whiteisthenewblack** [comment]
There are no plans for a GUI, the readme explains how to use the command line interface. If you have problems with that, you can open another issue :-)
