### ISSUE TITLE
Not finding user_auth_token

### ISSUE THREAD

**Issue by shillshocked** [whiteisthenewblack/qobuz-get#7]
There is no such get request described as in the instruction when inspecting the network window.

So far, I have seen:
dzr_uniq_id
sid
arl

as request cookies in firefox

In Chrome, there is:
api_token
cid

in gw-light.php...
Which one am I supposed to use? I've tried some and none have worked so far.

**Comment by whiteisthenewblack** [comment]
Are you using the latest instructions? The ones on git.fuwafuwa.moe were out of date. 

You need to load an album page and inspect the request beginning with `get?album_id`

**Comment by shillshocked** [comment]
OK...got there, now I am getting:
Looking up album...
Could not parse album data!

**Comment by shillshocked** [comment]
Nevermind...got it to work...had to get the full string for x-user-auth-token.

You have to expand the screen to see it all, otherwise there is a '...' in the string

Thanks for the help. :)
